# recomende vscode ext: github.vscode-github-actions

name: release

on:
  push:
    # branches:
    #   - main
    tags:
        - "[0-9]+.[0-9]+.[0-9]+"
        - 'v*'
defaults:
  run:
    shell: bash

jobs:
  release:
    name: release npm package
    # if: ${{ github.repository_owner == 'ymc-github' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # allow GITHUB_TOKEN to publish packages
    steps:
      - name: checkout your repository
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
      # - name: Create github Release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ steps.get_version.outputs.VERSION }}
      #     release_name: ${{ steps.get_version.outputs.VERSION }}
      #     draft: false
      #     prerelease: false

      # - name: Create Release 2
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: ${{ github.ref }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          version: ^7.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build npm Packages
        run: pnpm run build

      - name: Publish to registry.npmjs.org
        uses: JS-DevTools/npm-publish@v3
        with:
            token: ${{ secrets.NPM_TOKEN }}
            registry: "https://registry.npmjs.org/"

      - name: Publish to npm.pkg.github.com
        uses: JS-DevTools/npm-publish@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            registry: "https://npm.pkg.github.com"

    #   - name: publish to npmjs.com
    #     run: npm publish
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #       NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    #   - name: Create Release Pull Request or Publish
    #     id: changesets
    #     uses: changesets/action@v1
    #     with:
    #       version: pnpm run version
    #       publish: pnpm exec changeset publish
    #       commit: "[ci] release"
    #       title: "[ci] release"
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #       NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
